version: '3.8'

services:
  php83:
    image: pelso/php-dev-xdebug:8.3
    volumes: [ ../:/home/app/docroot ]
  php80:
    image: pelso/php-dev-xdebug:8.0
    volumes: [ ../:/home/app/docroot ]
  php72:
    image: pelso/php-dev-xdebug:7.2
    volumes: [ ../:/home/app/docroot ]
  php71:
    image: pelso/php-dev-xdebug:7.1
    volumes: [ ../:/home/app/docroot ]
  php70:
    image: pelso/php-dev-xdebug:7.0
    volumes: [ ../:/home/app/docroot ]
  php56:
    image: pelso/php-dev-xdebug:5.6
    volumes: [ ../:/home/app/docroot ]